# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cadastro_pb2 as cadastro__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cadastro_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PortalCadastroStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NovoUsuario = channel.unary_unary(
                '/cadastro.PortalCadastro/NovoUsuario',
                request_serializer=cadastro__pb2.Usuario.SerializeToString,
                response_deserializer=cadastro__pb2.Status.FromString,
                _registered_method=True)
        self.EditaUsuario = channel.unary_unary(
                '/cadastro.PortalCadastro/EditaUsuario',
                request_serializer=cadastro__pb2.Usuario.SerializeToString,
                response_deserializer=cadastro__pb2.Status.FromString,
                _registered_method=True)
        self.RemoveUsuario = channel.unary_unary(
                '/cadastro.PortalCadastro/RemoveUsuario',
                request_serializer=cadastro__pb2.Identificador.SerializeToString,
                response_deserializer=cadastro__pb2.Status.FromString,
                _registered_method=True)
        self.ObtemUsuario = channel.unary_unary(
                '/cadastro.PortalCadastro/ObtemUsuario',
                request_serializer=cadastro__pb2.Identificador.SerializeToString,
                response_deserializer=cadastro__pb2.Usuario.FromString,
                _registered_method=True)
        self.ObtemTodosUsuarios = channel.unary_stream(
                '/cadastro.PortalCadastro/ObtemTodosUsuarios',
                request_serializer=cadastro__pb2.Vazia.SerializeToString,
                response_deserializer=cadastro__pb2.Usuario.FromString,
                _registered_method=True)
        self.NovoLivro = channel.unary_unary(
                '/cadastro.PortalCadastro/NovoLivro',
                request_serializer=cadastro__pb2.Livro.SerializeToString,
                response_deserializer=cadastro__pb2.Status.FromString,
                _registered_method=True)
        self.EditaLivro = channel.unary_unary(
                '/cadastro.PortalCadastro/EditaLivro',
                request_serializer=cadastro__pb2.Livro.SerializeToString,
                response_deserializer=cadastro__pb2.Status.FromString,
                _registered_method=True)
        self.RemoveLivro = channel.unary_unary(
                '/cadastro.PortalCadastro/RemoveLivro',
                request_serializer=cadastro__pb2.Identificador.SerializeToString,
                response_deserializer=cadastro__pb2.Status.FromString,
                _registered_method=True)
        self.ObtemLivro = channel.unary_unary(
                '/cadastro.PortalCadastro/ObtemLivro',
                request_serializer=cadastro__pb2.Identificador.SerializeToString,
                response_deserializer=cadastro__pb2.Livro.FromString,
                _registered_method=True)
        self.ObtemTodosLivros = channel.unary_stream(
                '/cadastro.PortalCadastro/ObtemTodosLivros',
                request_serializer=cadastro__pb2.Vazia.SerializeToString,
                response_deserializer=cadastro__pb2.Livro.FromString,
                _registered_method=True)


class PortalCadastroServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NovoUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditaUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtemUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtemTodosUsuarios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NovoLivro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditaLivro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveLivro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtemLivro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtemTodosLivros(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PortalCadastroServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NovoUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.NovoUsuario,
                    request_deserializer=cadastro__pb2.Usuario.FromString,
                    response_serializer=cadastro__pb2.Status.SerializeToString,
            ),
            'EditaUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.EditaUsuario,
                    request_deserializer=cadastro__pb2.Usuario.FromString,
                    response_serializer=cadastro__pb2.Status.SerializeToString,
            ),
            'RemoveUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveUsuario,
                    request_deserializer=cadastro__pb2.Identificador.FromString,
                    response_serializer=cadastro__pb2.Status.SerializeToString,
            ),
            'ObtemUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtemUsuario,
                    request_deserializer=cadastro__pb2.Identificador.FromString,
                    response_serializer=cadastro__pb2.Usuario.SerializeToString,
            ),
            'ObtemTodosUsuarios': grpc.unary_stream_rpc_method_handler(
                    servicer.ObtemTodosUsuarios,
                    request_deserializer=cadastro__pb2.Vazia.FromString,
                    response_serializer=cadastro__pb2.Usuario.SerializeToString,
            ),
            'NovoLivro': grpc.unary_unary_rpc_method_handler(
                    servicer.NovoLivro,
                    request_deserializer=cadastro__pb2.Livro.FromString,
                    response_serializer=cadastro__pb2.Status.SerializeToString,
            ),
            'EditaLivro': grpc.unary_unary_rpc_method_handler(
                    servicer.EditaLivro,
                    request_deserializer=cadastro__pb2.Livro.FromString,
                    response_serializer=cadastro__pb2.Status.SerializeToString,
            ),
            'RemoveLivro': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveLivro,
                    request_deserializer=cadastro__pb2.Identificador.FromString,
                    response_serializer=cadastro__pb2.Status.SerializeToString,
            ),
            'ObtemLivro': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtemLivro,
                    request_deserializer=cadastro__pb2.Identificador.FromString,
                    response_serializer=cadastro__pb2.Livro.SerializeToString,
            ),
            'ObtemTodosLivros': grpc.unary_stream_rpc_method_handler(
                    servicer.ObtemTodosLivros,
                    request_deserializer=cadastro__pb2.Vazia.FromString,
                    response_serializer=cadastro__pb2.Livro.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cadastro.PortalCadastro', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cadastro.PortalCadastro', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PortalCadastro(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NovoUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cadastro.PortalCadastro/NovoUsuario',
            cadastro__pb2.Usuario.SerializeToString,
            cadastro__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditaUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cadastro.PortalCadastro/EditaUsuario',
            cadastro__pb2.Usuario.SerializeToString,
            cadastro__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cadastro.PortalCadastro/RemoveUsuario',
            cadastro__pb2.Identificador.SerializeToString,
            cadastro__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtemUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cadastro.PortalCadastro/ObtemUsuario',
            cadastro__pb2.Identificador.SerializeToString,
            cadastro__pb2.Usuario.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtemTodosUsuarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cadastro.PortalCadastro/ObtemTodosUsuarios',
            cadastro__pb2.Vazia.SerializeToString,
            cadastro__pb2.Usuario.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NovoLivro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cadastro.PortalCadastro/NovoLivro',
            cadastro__pb2.Livro.SerializeToString,
            cadastro__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditaLivro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cadastro.PortalCadastro/EditaLivro',
            cadastro__pb2.Livro.SerializeToString,
            cadastro__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveLivro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cadastro.PortalCadastro/RemoveLivro',
            cadastro__pb2.Identificador.SerializeToString,
            cadastro__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtemLivro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cadastro.PortalCadastro/ObtemLivro',
            cadastro__pb2.Identificador.SerializeToString,
            cadastro__pb2.Livro.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtemTodosLivros(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cadastro.PortalCadastro/ObtemTodosLivros',
            cadastro__pb2.Vazia.SerializeToString,
            cadastro__pb2.Livro.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
