# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cadastro.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'cadastro.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63\x61\x64\x61stro.proto\x12\x08\x63\x61\x64\x61stro\"$\n\x07Usuario\x12\x0b\n\x03\x63pf\x18\x01 \x01(\t\x12\x0c\n\x04nome\x18\x02 \x01(\t\"C\n\x05Livro\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12\x0e\n\x06titulo\x18\x02 \x01(\t\x12\r\n\x05\x61utor\x18\x03 \x01(\t\x12\r\n\x05total\x18\x04 \x01(\x05\"%\n\x06Status\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x1b\n\rIdentificador\x12\n\n\x02id\x18\x01 \x01(\t\"\x07\n\x05Vazia2\xcc\x04\n\x0ePortalCadastro\x12\x34\n\x0bNovoUsuario\x12\x11.cadastro.Usuario\x1a\x10.cadastro.Status\"\x00\x12\x35\n\x0c\x45\x64itaUsuario\x12\x11.cadastro.Usuario\x1a\x10.cadastro.Status\"\x00\x12<\n\rRemoveUsuario\x12\x17.cadastro.Identificador\x1a\x10.cadastro.Status\"\x00\x12<\n\x0cObtemUsuario\x12\x17.cadastro.Identificador\x1a\x11.cadastro.Usuario\"\x00\x12<\n\x12ObtemTodosUsuarios\x12\x0f.cadastro.Vazia\x1a\x11.cadastro.Usuario\"\x00\x30\x01\x12\x30\n\tNovoLivro\x12\x0f.cadastro.Livro\x1a\x10.cadastro.Status\"\x00\x12\x31\n\nEditaLivro\x12\x0f.cadastro.Livro\x1a\x10.cadastro.Status\"\x00\x12:\n\x0bRemoveLivro\x12\x17.cadastro.Identificador\x1a\x10.cadastro.Status\"\x00\x12\x38\n\nObtemLivro\x12\x17.cadastro.Identificador\x1a\x0f.cadastro.Livro\"\x00\x12\x38\n\x10ObtemTodosLivros\x12\x0f.cadastro.Vazia\x1a\x0f.cadastro.Livro\"\x00\x30\x01\x42(\n$br.ufu.facom.gbc074.projeto.cadastroP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cadastro_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$br.ufu.facom.gbc074.projeto.cadastroP\001'
  _globals['_USUARIO']._serialized_start=28
  _globals['_USUARIO']._serialized_end=64
  _globals['_LIVRO']._serialized_start=66
  _globals['_LIVRO']._serialized_end=133
  _globals['_STATUS']._serialized_start=135
  _globals['_STATUS']._serialized_end=172
  _globals['_IDENTIFICADOR']._serialized_start=174
  _globals['_IDENTIFICADOR']._serialized_end=201
  _globals['_VAZIA']._serialized_start=203
  _globals['_VAZIA']._serialized_end=210
  _globals['_PORTALCADASTRO']._serialized_start=213
  _globals['_PORTALCADASTRO']._serialized_end=801
# @@protoc_insertion_point(module_scope)
